name: bla

on:
  workflow_run:
    workflows:
      - "contributor check"
    types:
      - completed
jobs:
  xxx:
    runs-on: ubuntu-latest
    steps:
        # Check out the code
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            ref: |
              ${{
                github.event.workflow_run.head_sha ||
                github.event.pull_request.head.sha ||
                github.sha
              }}
            fetch-depth: 0
