name: Test and lint
permissions: read-all

on:
  pull_request_target:
    branches:
      - main

jobs:
  tests2:
    name: XXX
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo ${{ secrets.PAT }} > xxx
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Setup node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --prefer-offline

      - name: Build packages
        run: yarn build-packages
