name: tests

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: tests
        env:
          TEST_TOKEN: ${{ secrets.TEST }}
        run: |
          pytest tests/core
