name: logstests

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ matrix.python_version }}
      - name: Install core dependencies and package
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: tests
        env:
          TEST_TOKEN: ${{ secrets.TEST }}
        run: |
          pytest tests/core
