name: PR Site Build

on:
    pull_request_target:
        branches:
            - fd-test
        types:
            - opened
            - synchronize
            - reopened
            - closed

env:
    PR_FOLDER: preview/${{github.event.pull_request.user.login}}-${{github.event.pull_request.head.ref}}

jobs:
    build:
        name: Build Site for PR
        runs-on: ubuntu-latest
        # Note: only run when trigger is 'pull_request' in case pull request is from the same repo (see https://github.com/orgs/community/discussions/26829#discussioncomment-3253575)
        if: (github.event_name == 'pull_request_target' || github.event.pull_request.base.repo.fork) && github.event.pull_request.merged != true && github.event.pull_request.state != 'closed'
        steps:
            - name: Checkout PR Code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{github.event.pull_request.head.sha}}
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: latest
                  cache: npm

            - name: Install Dependencies
              run: npm ci
