name: Py
on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]

defaults:
  run:
    shell: bash -x -e -u -o pipefail {0}

jobs:
  xxx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Setup Python env
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
