name: Validate quickstarts

on:
  workflow_run:
    workflows: ["Validation Gate"]
    types:
      - completed

env:
  COMMIT_SHA: ${{ github.event.workflow_run.head_commit.id }}

jobs:
  ensure-quickstart-ids-are-unique:
    name: Ensure quickstart ids are unique
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@268677152d06ba59fcec7a7f0b5d961b6ccd7e1e
        with:
          workflow: validation_gate.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Get PR number
        id: get_pr_number
        run: |
          export PR_NUMBER=$(cat artifact/pr_number.txt)
          echo "pr-number=$PR_NUMBER" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          ref: "refs/pull/${{ env.pr-number }}/merge"

      - name: Setup workspace
        uses: "./.github/actions/bootstrap"

      - name: Check for unique names and ids
        id: validation
        run: cd utils && yarn check-quickstart-uniqueness
